/**
 * The call-out line shown with every number.
 *
 * Traditional housie calls are British ("two little ducks", "legs eleven").
 * These are re-cut for an Indian table. Edit freely - this file has no logic
 * in it and changing a line cannot break a game.
 */
export const TAGLINES = {
  1: 'Ekka! Akela hai, par kaafi hai.',
  2: 'Do! Ek do teen...',
  3: 'Teen Patti!',
  4: 'Chaar sau bees ka chaar - zara sambhal ke.',
  5: 'Paanch! High five.',
  6: 'Chakka! Out of the stadium.',
  7: 'Saat samundar paar.',
  8: 'Aath! Ashtami special.',
  9: 'Nau do gyarah.',
  10: 'Dus ka dum!',
  11: 'Gyarah - do chhote bhai side by side.',
  12: 'Baarah - ek dozen samose.',
  13: 'Terah - unlucky for some, jackpot for one.',
  14: 'Chaudah - Valentine ka din.',
  15: 'Pandrah August - azaadi!',
  16: 'Sweet sixteen.',
  17: 'Satrah - teenage tantrum.',
  18: 'Atharah - ab vote daal sakte ho!',
  19: 'Unnees - bees se bas ek kam.',
  20: 'Bees! Poora score.',
  21: 'Ikkees - blackjack!',
  22: 'Baais - do battakh, quack quack.',
  23: 'Teis - thoda aur.',
  24: 'Chaubees - poora din, 24 ghante.',
  25: 'Pachchees - quarter century!',
  26: 'Chhabbees January - Republic Day.',
  27: 'Sattaees.',
  28: 'Atthaees.',
  29: 'Unattees - leap year ka intezaar.',
  30: 'Tees! Dirty thirty.',
  31: 'Ikattees - mahine ka aakhri din.',
  32: 'Battees - poore battees daant.',
  33: 'Tetees - do bandar jhoole par.',
  34: 'Chauntees.',
  35: 'Paintees - half time.',
  36: 'Chhattees - chhattees ka aankda!',
  37: 'Saintees.',
  38: 'Adhtees.',
  39: 'Unchalees.',
  40: 'Chalees - life begins at forty!',
  41: 'Ektalees.',
  42: 'Bayalees - the answer to everything.',
  43: 'Tentalees.',
  44: 'Chauwalees - do kursiyan saath saath.',
  45: 'Paintalees - aadha safar.',
  46: 'Chhiyalees.',
  47: 'Saitalees - 1947, yaad hai na?',
  48: 'Adtalees.',
  49: 'Unchaas.',
  50: 'Pachaas! Half century, taali bajao.',
  51: 'Ikyavan - shagun ka lifafa.',
  52: 'Bavan - taash ki poori gaddi.',
  53: 'Tirpan.',
  54: 'Chauvan.',
  55: 'Pachpan - do naagin!',
  56: 'Chhappan - chhappan inch ka seena.',
  57: 'Sattavan - 1857.',
  58: 'Athavan.',
  59: 'Unsath.',
  60: 'Saath - retirement time!',
  61: 'Iksath.',
  62: 'Basath.',
  63: 'Tirsath.',
  64: 'Chausath - shatranj ke chausath khaane.',
  65: 'Painsath.',
  66: 'Chhiyasath - do chakke, chhakka chhakka!',
  67: 'Sarsath.',
  68: 'Adsath.',
  69: 'Unhattar - upar neeche, neeche upar.',
  70: 'Sattar - dadaji ki umar.',
  71: 'Ikhattar.',
  72: 'Bahattar.',
  73: 'Tihattar.',
  74: 'Chauhattar.',
  75: 'Pachhattar - platinum!',
  76: 'Chhihattar.',
  77: 'Satattar - do jhande.',
  78: 'Athhattar.',
  79: 'Unasi - assi se ek kam.',
  80: 'Assi! Ab toh bas thoda sa.',
  81: 'Ikyasi.',
  82: 'Bayasi.',
  83: 'Tirasi - 1983, World Cup!',
  84: 'Chaurasi - chaurasi lakh yoniyan.',
  85: 'Pachasi.',
  86: 'Chhiyasi.',
  87: 'Satasi.',
  88: 'Athasi - do motu saath saath.',
  89: 'Nawasi - bas ek aur!',
  90: 'Nabbe! Top of the board, aakhri number.',
};

/** Never returns undefined - a missing line must not break the board. */
export function taglineFor(value) {
  return TAGLINES[value] ?? `Number ${value}!`;
}
